### PR TITLE
Idempotency check for SPT Local Storage

### LINKED ISSUE #404: Creating Server profile for DLs fails
## Scenario/Intent

Hello,

I am trying to create SPT and SP for DLs servers using terraform modules. However, the terraform execution fails when creating the Server Profiles from their templates.

Note: during the workflow, the creation of the Server Profile Templates is successfull.

## Environment Details

- OneView Terraform SDK provider: v6.3.0-13 (build manually from the master branch)
- OneView Appliance Version: 6.10

## Expected Result

The Server Profiles for the DLs are configured using the previously created SPT.

## Actual Result
 
```
Error: An unexpected problem occurred and has been logged at approximately 2021-09-24 13:39:21.604 UTC. 
Retry the operation. If the problem persists, contact your authorized support representative and provide a support dump.

  on ../Server_Profile/main.tf line 1, in resource "oneview_server_profile" "ServerProfiles":
   1: resource "oneview_server_profile" "ServerProfiles" {
```

### PR DESCRIPTION
**Pull request by yuvirani**
### Description
Idempotency check for SPT Local Storage

### Check List
- [ ] New functionality includes testing.
  - [ ]  All tests pass for go 1.11 + gofmt checks.
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in the examples (please include helpful comments).
  - [ ] New endpoints supported are updated in the endpoints-support.md file.
- [ ] Changes are documented in the CHANGELOG.

### CODE REVIEW

**Review by AsisBagga — COMMENTED** [review]
Can particular reason why Typeset is changed?

I believe, TypeSet should not be converted to TypeList as this will cause issues for deleting middle and first blocks in a list. The use-case for local storage and controller is completely different.

**Review by nabhajit-ray — APPROVED** [review]
LGTM

File: oneview/resource_server_profile_template.go [hunk 1]
```diff
@@ -2880,7 +2891,15 @@ func resourceServerProfileTemplateUpdate(d *schema.ResourceData, meta interface{
 						Name:              logicalDrivesItem["name"].(string),
 						NumPhysicalDrives: logicalDrivesItem["num_physical_drives"].(int),
 						NumSpareDrives:    logicalDrivesItem["num_spare_drives"].(int),
-						SasLogicalJBODId:  logicalDrivesItem["sas_logical_jbod_id"].(int),
+					}
+					if logicalDrivesItem["sas_logical_jbod_id"].(string) != "" {
```
Comment (AvijitOS) [inline oneview/resource_server_profile_template.go:2895]: create and update follow similar piece of code...can't we put it into a function and call it in both the place?

File: oneview/resource_server_profile_template.go [hunk 2]
```diff
@@ -2306,9 +2315,11 @@ func resourceServerProfileTemplateRead(d *schema.ResourceData, meta interface{})
 					"name":                spt.LocalStorage.Controllers[i].LogicalDrives[j].Name,
 					"num_physical_drives": spt.LocalStorage.Controllers[i].LogicalDrives[j].NumPhysicalDrives,
 					"num_spare_drives":    spt.LocalStorage.Controllers[i].LogicalDrives[j].NumSpareDrives,
-					"sas_logical_jbod_id": spt.LocalStorage.Controllers[i].LogicalDrives[j].SasLogicalJBODId,
 					"raid_level":          spt.LocalStorage.Controllers[i].LogicalDrives[j].RaidLevel,
 				})
+				if spt.LocalStorage.Controllers[i].LogicalDrives[j].SasLogicalJBODId != 0 {
```
Comment (AvijitOS) [inline oneview/resource_server_profile_template.go:2320]: in line 2309, we are assigning from OV and then here we are modifying it after converting into string. Can't we deal with it in line 2309 only

Comment (yuvirani) [reply oneview/resource_server_profile_template.go:2320]: Since LogicalDrives is a TypeSet, we must iterate and validate for each logicalDrives sas_logical_jbod_id attribute. So, we cant check it directly.

Comment (AvijitOS) [reply oneview/resource_server_profile_template.go:2320]: "sas_logical_jbod_id": strconv.Itoa(spt.LocalStorage.Controllers[i].LogicalDrives[j].SasLogicalJBODId) will not work? only issue I can see adding of if condition in single line...generally ternary operators...but not sure in GoLang those are not simple....ok with current code

**Review by AvijitOS — APPROVED** [review]

File: oneview/resource_server_profile_template.go [hunk 3]
```diff
@@ -1569,8 +1569,17 @@ func resourceServerProfileTemplateCreate(d *schema.ResourceData, meta interface{
...
 						NumPhysicalDrives: logicalDrivesItem["num_physical_drives"].(int),
 						NumSpareDrives:    logicalDrivesItem["num_spare_drives"].(int),
-						SasLogicalJBODId:  logicalDrivesItem["sas_logical_jbod_id"].(int),
 					})
+					if logicalDrivesItem["sas_logical_jbod_id"].(string) != "" {
+						val, err := strconv.Atoi(logicalDrivesItem["sas_logical_jbod_id"].(string))
+						if err != nil {
+							return fmt.Errorf("invalid sas_logical_jbod_id: %s", err)
+						}
+						logicalDrives = append(logicalDrives, ov.LogicalDriveV3{
```
Comment (AsisBagga) [inline oneview/resource_server_profile_template.go:1578]: This is incorrect. 
You are doing append operations in case of sas_logical_jbod_id
have you tested this if it works?

File: oneview/resource_server_profile_template.go (hunk 2 above)
Comment (AsisBagga) [reply oneview/resource_server_profile_template.go:2320]: @AvijitOS in case of an empty string, it will panic (because "" cant be converted to a number). Need an exception to bypass a panic.

File: oneview/resource_server_profile_template.go [hunk 4]
```diff
@@ -2880,7 +2891,15 @@ func resourceServerProfileTemplateUpdate(d *schema.ResourceData, meta interface{
...
 						NumPhysicalDrives: logicalDrivesItem["num_physical_drives"].(int),
 						NumSpareDrives:    logicalDrivesItem["num_spare_drives"].(int),
-						SasLogicalJBODId:  logicalDrivesItem["sas_logical_jbod_id"].(int),
+					}
+					if logicalDrivesItem["sas_logical_jbod_id"].(string) != "" {
+						val, err := strconv.Atoi(logicalDrivesItem["sas_logical_jbod_id"].(string))
+						if err != nil {
+							return fmt.Errorf("invalid sas_logical_jbod_id: %s", err)
+						}
+						logicalDrives = append(logicalDrives, ov.LogicalDriveV3{
```
Comment (AsisBagga) [inline oneview/resource_server_profile_template.go:2900]: Same as above.

**Review by AsisBagga — COMMENTED** [review]
Please update the change log as well for this issue,

File: oneview/resource_server_profile_template.go (hunk 2 above)
Comment (AsisBagga) [reply oneview/resource_server_profile_template.go:2320]: and that's true we can use ternary operator, but I am not sure if it will work while assigning value to a struct like below
``x := anySturct{ myIntStructVar: MyLocalVar > 0 ? 1 : 0 }``

**Review by AsisBagga — APPROVED** [review]
Please update tha changelog with issue details.
