### PR TITLE
Issue 387 fix

### LINKED ISSUE #387: Unable to import server hardware
Unable to import server hardware. 

Terraform version: 0.13.7
SDK version: master/v6.2
Go version:  v1.15.7

Error:- 
```
oneview_server_hardware.server_hardware --
oneview_server_hardware.server_hardware: Importing from ID "--"...
oneview_server_hardware.server_hardware: Import prepared!
  Prepared oneview_server_hardware for import
oneview_server_hardware.server_hardware: Refreshing state... [id=--]
Error: Cannot import non-existent remote object

While attempting to import an existing object to
oneview_server_hardware.server_hardware, the provider detected that no object
exists with the given id. Only pre-existing objects can be imported; check
that the id is correct and that it is associated with the provider's
configured region or endpoint, or use "terraform apply" to create a new remote
object for this resource.
```

### PR DESCRIPTION
**Pull request by AsisBagga**
### Description
Issue fix for #387 

### Issues Resolved
#387 

### Check List
- [ ] New functionality includes testing.
  - [ ]  All tests pass for go 1.11 + gofmt checks.
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in the examples (please include helpful comments).
  - [ ] New endpoints supported are updated in the endpoints-support.md file.
- [ ] Changes are documented in the CHANGELOG.

### CODE REVIEW

File: oneview/resource_server_hardware.go [hunk 1]
```diff
@@ -200,14 +202,32 @@ func resourceServerHardwareCreate(d *schema.ResourceData, meta interface{}) erro
...
+	}
+
 	if err != nil || servHard.URI.IsNil() {
 		d.SetId("")
-		return nil
+		return fmt.Errorf("unable to retrieve server hardware %s", err)
 	}
-	d.SetId(d.Id())
+	// setting UUID as resource Id
+	d.SetId(servHard.UUID.String())
```
Comment (AvijitOS) [inline oneview/resource_server_hardware.go:229]: looks like we are setting uuid as id rather than name...have we looked into it clearly...because if we set uuid as id then not sure how GetServerHardwareByName(d.id()) will work?

**Review by AvijitOS — COMMENTED** [review]
need to have discussions on this implementation

**Review by AvijitOS — APPROVED** [review]
After the discussion I understood the scenario so I am ok with it

File: oneview/resource_server_hardware.go [hunk 2]
```diff
@@ -200,14 +202,32 @@ func resourceServerHardwareCreate(d *schema.ResourceData, meta interface{}) erro
...
+	)
 	config := meta.(*Config)
 
-	servHard, err := config.ovClient.GetServerHardwareByName(d.Get("hostname").(string))
+	// fetching server hardware hostname incase it's added
+	if val, ok := d.GetOk("hostname"); ok {
+		servHard, err = config.ovClient.GetServerHardwareByName(val.(string))
+	} else {
+		// for refreshing imported server hardware we would need it's name
+		if val, ok := d.GetOk("name"); ok {
```
Comment (yuvirani) [inline oneview/resource_server_hardware.go:216]: When name attribute is Computed, how do we update TF configuration file with this attribute? If we are importing using the name, then we can directly refresh the resource without name. Whats the use of this block?

Comment (AsisBagga) [reply oneview/resource_server_hardware.go:216]: name is computed so once a user import any SH name will get update and we are setting ID as UUID. 
so for 2nd time plan, we are using name from state to do a GET operation.

**Review by yuvirani — APPROVED** [review]
