### PR TITLE
LIG Read Issue for Terraform 0.11 #285

### LINKED ISSUE #285: Terraform crashes for Logical Interconnect Group Read
OV: v6.0.0
terraform-provider-oneview: v6.0.0-12 and v6.0.0-11

Current Situation: Terraform crashed while performing Read due to improper collection of Qos Attributes.

### PR DESCRIPTION
**Pull request by AsisBagga**
### Description
TF Crashes for Read in LIG due to the bug in LIG Read method while collecting Qos attributes.
This Pr is for Terraform-0.11 branch

This PR fixed formatting issues in below files as well :-

oneview/data_source_interconnect_type.go
oneview/data_source_logical_interconnect_group.go
oneview/data_source_server_profile.go
oneview/data_source_server_profile_template.go
oneview/data_source_storage_pool.go
oneview/resource_enclosure_group.go
oneview/resource_ethernet_network.go
oneview/resource_fc_network.go
oneview/resource_fcoe_network.go
oneview/resource_hypervisor_cluster_profile.go
oneview/resource_network_set.go
oneview/resource_server_profile.go
oneview/resource_storage_pool.go
 oneview/resource_uplink_set.go

### Issues Resolved
#285 

### Check List
- [x] New functionality includes testing.
  - [x]  All tests pass for go 1.11 + gofmt checks.
- [x] New functionality has been documented in the README if applicable.
  - [x] New functionality has been thoroughly documented in the examples (please include helpful comments).
  - [x] New endpoints supported are updated in the endpoints-support.md file.
- [x] Changes are documented in the CHANGELOG.

### CODE REVIEW

File: oneview/resource_logical_interconnect_group.go [hunk 1]
```diff
@@ -651,79 +724,6 @@ func resourceLogicalInterconnectGroup() *schema.Resource {
 					},
 				},
 			},
-			"port_flap_settings": {
```
Comment (VenkateshRavula) [inline oneview/resource_logical_interconnect_group.go:654]: Is the swapping of ```port_flap_settings``` up an down made intentionally..? Just asking because I didn't find any changes between the removed lines and added lines.

File: .github/workflows/CICD.yml [hunk 2]
```diff
@@ -34,7 +34,10 @@ jobs:
         GOPATH: /home/runner/work/HewlettPackard/terraform-provider-oneview/go
 
     - name: Go formatting checks
-      run: if [ ! -z "$(find . -type f -name "*.go" -not -path "./vendor/*" | sed "s|^\./||" | xargs gofmt -l)" ]; then exit 1; fi
+      run: if ! [ -z "$(find . -type f -name "*.go" -not -path "./vendor/*" | sed "s|^\./||" | xargs gofmt -l)" ]; then 
+                    echo  -e " $(find . -type f -name "*.go" -not -path "./vendor/*" | sed "s|^\./||" | xargs gofmt -l)";
```
Comment (VenkateshRavula) [inline .github/workflows/CICD.yml:38]: what does this new line add to existing behavior..?

Comment (nabhajit-ray) [reply .github/workflows/CICD.yml:38]: It checks for gomft errors. If there are any gofmt error, build will exit with error

**Review by VenkateshRavula — APPROVED** [review]

**Review by nabhajit-ray — APPROVED** [review]
