### PR TITLE
Issue 272 295 Fix for provider on TF13

### LINKED ISSUE #272: more server profile/template issues not working as expected
if I create a server profile template with local storage or bios settings terraform properly creates it.
but if I go into the GUI and modify a storage/bios setting and then re-run the plan terraform should re-evaluate the actual configuration and report the settings drift.  A subsequent terraform apply should remediate the drift either through modifying the resource attributes, or forcing a new resource (delete/recreate)

This does not seem to happen and terraform reports back no changes as if the above process is not working as expected.

Let me know if there is anything else you need.

@AsisBagga @nabhajit-ray

### PR DESCRIPTION
**Pull request by AsisBagga**
### Description
Issue 272 295 Fix for provider on TF13
Along with issue fix this PR refactor the Read for Server Profile Resource on both data source and resource files. 

### Issues Resolved
#272 
#295 

### Check List
- [x] New functionality includes testing.
  - [x]  All tests pass for go 1.11 + gofmt checks.
- [x] New functionality has been documented in the README if applicable.
  - [x] New functionality has been thoroughly documented in the examples (please include helpful comments).
  - [x] New endpoints supported are updated in the endpoints-support.md file.
- [x] Changes are documented in the CHANGELOG.

### CODE REVIEW

**Review by VenkateshRavula — APPROVED** [review]

File: oneview/data_source_server_profile_template.go [hunk 1]
```diff
@@ -136,7 +345,7 @@ func dataSourceServerProfileTemplate() *schema.Resource {
 						"controller": {
 							Optional: true,
 							Type:     schema.TypeList,
-							MaxItems: 1,
+							//							MaxItems: 1,
```
Comment (nabhajit-ray) [inline oneview/data_source_server_profile_template.go:348]: remove this if not required

**Review by nabhajit-ray — APPROVED** [review]
